name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        # deploy_sh.sh [repository_name] OR deploy_home.sh (deploys my custom links page to server root)
        script: 'cd ~/projects/cervel/ && ./deploy.sh [repository_name]'